version: "3.8"

services:
  node:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: yumemi-coding-test
    ports:
      - "3000:3000"
      - "6006:6006"
    volumes:
      - ./app:/home/app
      - node_modules_volume:/home/app/node_modules:delegated
      - build_volume:/home/app/build:nocopy
  json-server:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: yumemi-coding-test-json-server
    ports:
      - 4000:4000
    volumes:
      - ./app:/home/app
      - node_modules_volume:/home/app/node_modules:delegated
      - build_volume:/home/app/build:nocopy
    command: yarn json-server

volumes:
  node_modules_volume:
  build_volume: