# https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-react-and-next

name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.12.0'

      - name: 'Build and Deploy'
        working-directory: ./app
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn build:storybook
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/build/